### ISSUE TITLE
variable configuration

### ISSUE THREAD

**Issue by hehehehe123** [alibabacloud-automation/terraform-alicloud-vpc#10]
Hi' 
  Thank you for offer this module. I'm confused when i use this module. By default setting, it will appear an error when i run the command: terraform plan. 
configuration is as fellow:
    destination_cidrs = "${var.destination_cidrs}"
    nexthop_ids = "${var.server_ids}"
 I config the variable destination_cidrs with a ip network segment in the variable.tf file. but it can not work. It sames that the root main file can not reference the module variables. When I derect to set the 'destination_cidrs' and 'nexthop_ids' to a net segment. It can be work fine.  Did you have some suggest for me. Thank you very much.

**Comment by xiaozhu36** [comment]
HI . @hehehehe123 Can you show me the error details?

**Comment by hehehehe123** [comment]
hi @xiaozhu36  When i run the command: terraform init, it will shows the error message as fellow:
Error: module 'vpc-test': unknown variable referenced: 'destination_cidrs'; define it with a 'variable' block
Did it can not reference the module variable value?
Thanks for reply.
