### ISSUE TITLE
add repo description

### ISSUE THREAD

**Issue by cgriggs01** [alibabacloud-automation/terraform-alicloud-vpc#6]
Can you please add a short repo description so that it can be seen in the icon view of within the Terraform registry. 

Once you've add a description, you'll need to create a new version/tag in order for the registry to pull the edited repository information. 

Thanks,
Chris

**Comment by xiaozhu36** [comment]
Hi @cgriggs01 

Thank you for your advice. I will do it.

Regards,
He Guimin
